#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************

CONFIG_TEST = y
CONFIG_MAIN = y

# Variables provided for Makefile
C_SOURCE := main.c

C_PATH := -Isdl/include/SDL2

LD_FLAG :=  -lmingw32 -lSDL2main -lSDL2.dll

LIB_PATH := -Lsdl/lib

