#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************

CONFIG_MACRO_A = 1
CONFIG_MACRO_B = 'n'

# Variables provided for Makefile
C_SOURCE := macro.c macro_a.c macro_b.c
