//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define    CONFIG_MACRO_A                     1
#define    CONFIG_MACRO_B                     n


#endif  //!__CONFIG_H__
