#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************


# Variables provided for Makefile
C_SOURCE := hello.c
