//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__




#endif  //!__CONFIG_H__
