//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define    COMPILER                           gcc
#define    CONFIG_DEBUG                       1
#define    CONFIG_LOG_LEVEL                   0
#define    CONFIG_MEM_POOL_SIZE               20
#define    CONFIG_MACRO_CACHE_SIZE            100


#endif  //!__CONFIG_H__
